### ISSUE TITLE
Issue collaborativa

### ISSUE THREAD

**Issue by Manuela1968** [Manuela1968/analista-programmatore-2023#1]
ciao .... isssue collaborativa :)  .... ci sei?

**Comment by alinabosinceanu** [comment]
QUESTA ISSUE DEVE ESSERE PROCESSATA DA UN COLLEGA

**Comment by Manuela1968** [comment]
ottimooooooooo!!! funzionaaa!!!!

**Comment by alinabosinceanu** [comment]
/

[ ] _``_
"LA VIE EST BELLE"

**Comment by Manuela1968** [comment]
oook allora tutto bene ..... alla prossima <3
